open_quiz:
  cron: "* * * * *"
  class: "OpenQuiz"
  description: "Open Pending Quiz"

live_quiz:
  cron: "* * * * *"
  class: "GoLiveQuiz"
  description: "Go Live Quiz"

close_quiz:
  cron: "* * * * *"
  class: "CloseQuiz"
  description: "Close Live Quiz"